### ISSUE TITLE
VTK Writer

### ISSUE THREAD

**Issue by sifanexisted** [agdestein/IncompressibleNavierStokes.jl#128]
Hi! Thank you for this fantastic package!

I ran into a problem using `vtk_writer` to save the velocity field from my simulation. The u and v components in the output look the same, which doesn’t seem right.

This happened while I was working on a Rayleigh–Taylor problem. Could this be a bug, or is there something I might be missing? Let me know if you need any code or output files to help figure it out. Thanks a lot!

```
        vtk = vtk_writer(;
        setup,
        dir = outdir,
        nupdate = 200,
        fieldnames = (:velocity, :temperature, :pressure),
        filename = "solution"
    )
```

<img width="728" alt="Screenshot 2024-12-19 at 3 22 37 PM" src="https://github.com/user-attachments/assets/567bab69-235d-409b-85eb-c1f7e1d53b9f" />

<img width="718" alt="Screenshot 2024-12-19 at 3 22 55 PM" src="https://github.com/user-attachments/assets/ef380320-07ed-4d38-8ee7-704db522dfea" />

**Comment by agdestein** [comment]
Thanks for the feedback!

This should be fixed now, let me know if you encounter further errors.
