### ISSUE TITLE
Error while 'using IncompressibleNavierStokes'

### ISSUE THREAD

**Issue by Hemadityamalla** [agdestein/IncompressibleNavierStokes.jl#37]
Hi,
I am exploring the package by following the instructions from https://agdestein.github.io/IncompressibleNavierStokes.jl/dev/generated/LidDrivenCavity2D/
I am using Julia version 1.5.3.
When I type `add IncompressibleNavierStokes`, I get no errors. 
However, when I type `using IncompressibleNavierStokes`, I get the following error:

`ERROR: LoadError: LoadError: syntax: invalid assignment location "; hx, hy" around /home/hemaditya/.julia/packages/IncompressibleNavierStokes/d4l3M/src/grid/max_size.jl:7
Stacktrace:
 [1] top-level scope at /home/hemaditya/.julia/packages/IncompressibleNavierStokes/d4l3M/src/grid/max_size.jl:1
 [2] include at ./Base.jl:368 [inlined]
 [3] include(::String) at /home/hemaditya/.julia/packages/IncompressibleNavierStokes/d4l3M/src/IncompressibleNavierStokes.jl:7
 [4] top-level scope at /home/hemaditya/.julia/packages/IncompressibleNavierStokes/d4l3M/src/IncompressibleNavierStokes.jl:28
 [5] top-level scope at none:2
 [6] eval at ./boot.jl:331 [inlined]
in expression starting at /home/hemaditya/.julia/packages/IncompressibleNavierStokes/d4l3M/src/grid/max_size.jl:1
in expression starting at /home/hemaditya/.julia/packages/IncompressibleNavierStokes/d4l3M/src/IncompressibleNavierStokes.jl:28`

It seems that the error arises when trying to include the max_size.jl function. Could you please help me around this error, since I am not yet an expert in Julia programming syntax?

Cheers

**Comment by agdestein** [comment]
Hi!
This package currently only works with Julia version 1.7 and above.
The `(; a, b) = x` syntax (short for `a = x.a`, `b = x.b`) was introduced in Julia version 1.7.
You may consider upgrading to the latest stable version of Julia, see <https://julialang.org/downloads/>.

**Comment by Hemadityamalla** [comment]
Hi,
Thanks for the reply! I've upgraded Julia to 1.8.3 and I was able to overcome the above error. However, I have a new error when I execute the following command on my commandline (I am trying to run the example simulations),
`julia-1.8.3 LidDrivenCavity2D.jl`,
I get the following error:
`Initial momentum residual = 0.05090339915871585
Iteration 1: momentum residual = 0.001034056530787347
Iteration 2: momentum residual = 0.0007818325375434987
Iteration 3: momentum residual = 0.000433200204905297
Iteration 4: momentum residual = 0.00023474593881534677
Iteration 5: momentum residual = 6.171949594050612e-5
Iteration 6: momentum residual = 7.567541449404942e-6
Iteration 7: momentum residual = 7.188702377374781e-9
Iteration 8: momentum residual = 1.0731243367881338e-14
ERROR: LoadError: UndefVarError: StateObserver not defined
`.


It seems that the function `StateObserver` is not being exported/loaded. 
When manually loading the IncompressibleNavierStokes library (`using IncompressibleNavierStokes`) in the julia shell, I couldnt find the StateObserver variable/function. 

Could you help me out with what is happening?

**Comment by agdestein** [comment]
That function is not yet included in the latest release (`v0.2`), I can tag a release later so it becomes available.

In the meantime, you can try the example from the stable docs, see
<https://agdestein.github.io/IncompressibleNavierStokes.jl/stable/generated/LidDrivenCavity2D/>.
There it should be without the `StateObserver` interface. The script file is available here:
<https://github.com/agdestein/IncompressibleNavierStokes.jl/blob/v0.2.0/examples/LidDrivenCavity2D.jl>.

**Comment by Hemadityamalla** [comment]
Hi, 
Thanks for the information! I was able to get it working now. 

Cheers!
