### ISSUE TITLE
UndefineVer

### ISSUE THREAD

**Issue by Khurramcoder** [agdestein/IncompressibleNavierStokes.jl#40]
ERROR: UndefVarError: `StateObserver` not defined
Stacktrace:
 [1] top-level scope
   @ f:\IncompressibleNavierStokes.jl-main\examples\Actuator2D.jl:87
i m using julia v1.9 facing above error

**Comment by agdestein** [comment]
Hi! Than you for the feedback. That feature was not yet included in `v0.2`, but should be available in `v0.3` just released. In a Julia REPL, you can try to to type `] up` to update to the latest version.

**Comment by Khurramcoder** [comment]
Thanks working nice
